/*
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

var mr = require('mori');

// memoized fibonacci
var fibonacci = (function () {
  var cache = mr.hash_map(0, 1, 1, 2);

  function fib(n) {
    var value = mr.get(cache, n);
    if (value !== null) {
      return value;
    }
    var result = fib(n - 1) + fib(n - 2);
    cache = mr.assoc(cache, n, result);
    return result;
  }

  return fib;
}());

function solve() {
  var fib_nums = mr.take_while(function (n) {
    return n < 4000000;
  }, mr.map(fibonacci, mr.range()));
  return mr.reduce(mr.sum, mr.filter(mr.is_even, fib_nums));
}

console.log('Answer:', solve());
